# Docs for this workflow are here https://github.com/github/issue-labeler
name: Triage Labels
on:
  issues:
    types:
      - opened
      - edited
jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Check Labels
        id: check-labels
        shell: bash
        run: |
          NAMES="${{ toJSON(github.event.issue.labels.*.name) }}"
          echo $NAMES
        if: steps.check-labels.outputs.match == 'true'
        uses: github/issue-labeler@v2.5
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/labeler.yml
          enable-versioned-regex: 0
